Repository MicrosoftDocs/quantum-api, pull requests merged in 2021-03, with the labels that each got.

#10 Restoring index.md for the libraries
  .openpublishing.publish.config.json
  api/qsharp/index.md
Labels: Change sent to author, do-not-merge, quantum/prod

#11 push to live
  .openpublishing.publish.config.json
  api/qsharp/index.md
Labels: do-not-merge

#12 3/23 PM Publish
  api/qsharp/microsoft.quantum.bitwise.yml
  api/qsharp/microsoft.quantum.chemistry.jordanwigner.vqe.yml
  api/qsharp/microsoft.quantum.chemistry.jordanwigner.yml
  api/qsharp/microsoft.quantum.chemistry.yml
  api/qsharp/microsoft.quantum.environment.yml
  api/qsharp/microsoft.quantum.extensions.bitwise.yml
  api/qsharp/microsoft.quantum.extensions.convert.yml
  api/qsharp/microsoft.quantum.extensions.math.yml
  api/qsharp/microsoft.quantum.machinelearning.datasets.yml
  api/qsharp/microsoft.quantum.machinelearning.yml
  api/qsharp/microsoft.quantum.research.characterization.yml
Labels: do-not-merge, review-team-triage

#15 3/24 PM Publish
  api/qsharp/microsoft.quantum.amplitudeamplification.yml
Labels: do-not-merge, review-team-triage

#19 3/31 PM Publish
  api/docfx.json
Labels: do-not-merge
