Repository MicrosoftDocs/quantum-api, pull requests merged in 2022-11, with the labels that each got.

#68 Please use Azure product-level header
  api/docfx.json
Labels: do-not-merge, needs-human-review, review-team-triage

#77 11/08 PM Publish
  api/docfx.json
Labels: do-not-merge, review-team-triage

#81 11/16 PM Publish
  api/index.md
Labels: do-not-merge, Change sent to author, qsharp/prod

#82 11/17 AM Publish
  api/index.md
Labels: do-not-merge, Change sent to author, qsharp/prod

#83 11/23 PM Publish
  api/index.md
Labels: do-not-merge, Change sent to author, qsharp/prod
