Repository MicrosoftDocs/quantum-api, pull requests merged in 2024-09, with the labels that each got.

#135 Remove locale codes from redirects
  .openpublishing.redirection.json
  api/TOC.yml
  api/dot-net-libraries.md
Labels: do-not-merge, needs-human-review

#136 Remove q# library landing page - no significant content
  .openpublishing.redirection.json
  api/TOC.yml
  api/index.md
Labels: do-not-merge

#138 clean up landing page
  api/TOC.yml
  api/index.md
  api/qsharp-lang/index.md
Labels: do-not-merge, needs-human-review

#137 9/12/2024 PM Publish
  .openpublishing.redirection.json
  api/TOC.yml
  api/dot-net-libraries.md
  api/index.md
  api/qsharp-lang/index.md
Labels: do-not-merge, Change sent to author, qsharp/svc
